{% set version = "0.0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-destinie
  version: {{ version|replace("-", "_") }}

source:
  # no tag is available (2020-02-21)
  url: https://github.com/nosretraites/Destinie-2/archive/588198941ced3926fcb57c360d41a82e588bef77.tar.gz
  sha256: cb63b6bcb612abac904c28bd1afbb864e06642d098b7dff2811cf51066385277
  patches:
    - 0001-Replace-PI-by-M_PI-as-per-STRICT_R_HEADERS.patch

build:
  number: 2
  merge_build_host: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('cxx') }}  # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - posix  # [win]
    - pkg-config
  host:
    - r-base
    - r-rcpp
    - r-openxlsx
    - r-xlsx
    - r-dplyr
    - r-tidyr
    - r-ggplot2
    - r-stringr
    - r-reshape2
    - r-rjava
  run:
    - r-base
    - r-rcpp
    - r-openxlsx
    - r-xlsx
    - r-dplyr
    - r-tidyr
    - r-ggplot2
    - r-stringr
    - r-reshape2
    - r-rjava

test:
  commands:
    - $R -e "library('destinie')"  # [not win]
    - R -e \"library('destinie')\"  # [win]

about:
  home: https://github.com/nosretraites/Destinie-2
  license: GPL-3.0-only
  license_file: COPYING.txt
  summary: Dynamic microsimulation model
  license_family: GPL

extra:
  recipe-maintainers:
    - jschueller
    - conda-forge/r
