{% set version = "0.0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-destinie
  version: {{ version|replace("-", "_") }}

source:
  # no tag is available (2020-02-21)
  git_url: https://github.com/nosretraites/Destinie-2.git  # [unix]
  git_rev: 588198941ced3926fcb57c360d41a82e588bef77  # [unix]
  url: https://github.com/nosretraites/Destinie-2/archive/master.zip  # [win]
  sha256: d6012624fa3d0c46d1d8a8c840571319e26f1e9711c832ec1b2ec5faf399301c  # [win]

build:
  number: 1
  # osx: Error in close.connection(con) : invalid connection
  skip: true  # [osx]
  merge_build_host: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('cxx') }}  # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - posix  # [win]
    - pkg-config
  host:
    - r-base
    - r-rcpp
    - r-openxlsx
    - r-xlsx
    - r-dplyr
    - r-tidyr
    - r-ggplot2
    - r-stringr
    - r-reshape2
    - r-rjava
  run:
    - r-base
    - r-rcpp
    - r-openxlsx
    - r-xlsx
    - r-dplyr
    - r-tidyr
    - r-ggplot2
    - r-stringr
    - r-reshape2
    - r-rjava

test:
  commands:
    - $R -e "library('destinie')"  # [not win]
    - R -e \"library('destinie')\"  # [win]

about:
  home: https://github.com/nosretraites/Destinie-2
  license: GPL-3.0-only
  license_file: COPYING.txt
  summary: Dynamic microsimulation model
  license_family: GPL

extra:
  recipe-maintainers:
    - jschueller
    - conda-forge/r
